### ISSUE TITLE
通过最新版本脚本启用tuic,使用clash.meta连接时报错

### ISSUE THREAD

**Issue by Sirius2016** [mack-a/v2ray-agent#701]
## 1.问题描述
通过最新版本脚本启用tuic,使用clash.meta连接时报错。
脚本生成的tuic配置文件没有token字段。
```yaml
  - name: "459d3f4c_tuic"
    server: hp.cc
    type: tuic
    port: 24357
    uuid: 459d3f4c-d339-4da4-a620-84137e50ce29
    password: 459d3f4c-d339-4da4-a620-84137e50ce29
    alpn:
     - h3
    congestion-controller: bbr
    disable-sni: true
    reduce-rtt: true
    fast-open: true
    heartbeat-interval: 8000
    request-timeout: 8000
    max-udp-relay-packet-size: 1500
    max-open-streams: 100
    ip-version: dual
    smux:
        enabled: false
```

## 2.安装失败的log或者截图
![image](https://github.com/mack-a/v2ray-agent/assets/23203953/3ce91c6a-53a8-4bd0-865c-5f3f4545be5f)
