### ISSUE TITLE
脚本自带订阅调用同一个 provider1.yaml ，clash verge 切换配置后代理组不变

### ISSUE THREAD

**Issue by mybdye** [mack-a/v2ray-agent#715]
不按照模版提交，一律关闭，反馈之前请仔细翻阅[此文章](https://www.v2ray-agent.com/archives/1684115970026)、建议使用**21**卸载后重新尝试

## 1.问题描述
脚本自带订阅调用同一个 provider1.yaml ，clash verge 切换配置后代理组不变
## 2.安装失败的log或者截图
```
proxy-providers:
  provider1:
    type: http
    path: ./provider1.yaml
    url: https://abc.com/abc
    interval: 3600
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
```
## 3.系统版本
Debian 11
## 4.脚本版本
当前版本：v2.9.22
