### ISSUE TITLE
修改自动选择的test url

### ISSUE THREAD

**Issue by bettswang** [mack-a/v2ray-agent#938]
不按照模版提交，一律关闭，反馈之前请仔细阅读[脚本异常处理](https://www.v2ray-agent.com/archives/1684115970026)，[客户端使用教程](https://www.v2ray-agent.com/archives/1695534611317)、建议使用**20**卸载后重新尝试

## 1.问题描述
大佬你好，因为我在clashmeta for android下，测试延迟，direct总是读取不出来。我后面发现是自动测试的URL连接为：http://www.gstatic.com/generate_204 。因为clashmeta for android 软件端无法进行url测试链接的自定义。我想要自定义下发规则中的自动选择的test url，所以修改了服务端下的配置文件。然后重新在app端进行更新配置。实际测试还是direct 连接读取不出来。

```
/etc/v2ray-agent/subscribe/clashMetaProfiles
proxy-groups:
  - name: 手动切换
    type: select
    use:
      - narkatachc_provider
    proxies: null
  - name: 自动选择
    type: url-test
    url: http://www.apple.com/library/test/success.html
    interval: 36000
    tolerance: 50
    use:
      - narkatachc_provider
    proxies: null
```

## 2.安装失败的log或者截图

实际我在clashmeta for android下测试还是无法测通。

## 3.系统版本
ubuntu20.04
## 4.脚本版本
V3.2.7
